export const ImagePath = {
  Aicon: require("../assets/images/letterA.jpeg"),
  closeIcon: require("../assets/images/close.png"),
  // bottomIcon: require("../assets/images/bottomicon.j"),
  // bottomIcon2: require("../assets/images/bottomIcon2.png"),
  bottomIconfinal: require("../assets/images/bottomiconfinal.jpeg"),
  // linkedin: require("../assets/images/linkedin.png"),
  linkedin: require("../assets/images/linkedin.json"),
  // github: require("../assets/images/github.png"),
  github: require("../assets/images/github.json"),
  // native: require("../assets/images/Native.png"),
  native: require("../assets/images/ReactNative.json"),
  // flutter: require("../assets/images/flutter.jpg"),
  flutter: require("../assets/images/Flutter.json"),
  profilePic: require("../assets/images/profilepic.jpeg"),
  Option: require("../assets/images/more.png"),
  // Option: require("../assets/images/navbar.json"),
  BackIcon: require("../assets/images/backIcon.png"),
  // Agent: require("../assets/images/Agent.png"),
  // Adihex: require("../assets/images/Adihex.png"),
  // Shopmatic: require("../assets/images/shopmatic.png"),
  // TataMotors: require("../assets/images/tatamotors.png"),
  AboutIcon: require("../assets/images/about.json"),
  WorkIcon: require("../assets/images/work.json"),
  ContactIcon: require("../assets/images/contact.json"),
  sendMail: require("../assets/images/mail.json"),
};
